CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, city TEXT, birth INTEGER);
CREATE TABLE GRADE (id INTEGER PRIMARY KEY, GRADE
INTEGER);

INSERT INTO students VALUES (1, 'SHALOM', 'TEL AVIV', 1974);
INSERT INTO students VALUES (2, 'YURI', 'RAANANA', 1980);
INSERT INTO students VALUES (3, 'ANAT', 'RISHON', 1994);
INSERT INTO students VALUES (4, 'DANA', 'REHOVOT', 1990);
INSERT INTO students VALUES (5, 'OMER', 'JERUSALEM', 1987);
 
 INSERT INTO GRADE VALUES (1, 95);
 INSERT INTO GRADE VALUES (2, 70);
 INSERT INTO GRADE VALUES (3, 85);
 INSERT INTO GRADE VALUES (4, 99);
 INSERT INTO GRADE VALUES (5, 91);

SELECT AVG(GRADE) from GRADE

ALTER TABLE GRADE ADD COLUMN EXCELLENT;

UPDATE GRADE SET EXCELLENT='yes' WHERE grade > 90;
UPDATE GRADE SET EXCELLENT='no' WHERE grade < 90;


