CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, city TEXT, birth INTEGER);

INSERT INTO students VALUES (1, 'SHALOM', 'TEL AVIV', 1974);
INSERT INTO students VALUES (2, 'YURI', 'RAANANA', 1980);
INSERT INTO students VALUES (3, 'ANAT', 'RISHON', 1994);
INSERT INTO students VALUES (4, 'DANA', 'REHOVOT', 1990);
INSERT INTO students VALUES (5, 'OMER', 'JERUSALEM', 1987);

DROP TABLE if exists students