CREATE TABLE Students (ID INTEGER PRIMARY KEY, NAME TEXT, CITY TEXT, BIRTH
INTEGER);

INSERT INTO Students (ID, NAME, CITY, BIRTH) VALUES (1, 'SHALOM', 'TEL AVIV', 1974);
INSERT INTO Students (ID, NAME, CITY, BIRTH) VALUES (2, 'YURI', 'RAANANA', 1980);
INSERT INTO Students (ID, NAME, CITY, BIRTH) VALUES (3, 'ANAT', 'RISHON', 1994);
INSERT INTO Students (ID, NAME, CITY, BIRTH) VALUES (4, 'DANA', 'REHOVOT', 1990);
INSERT INTO Students (ID, NAME, CITY, BIRTH) VALUES (5, 'OMER', 'JERUSALEM', 1987);

INSERT INTO Grade (ID, GRADE) VALUES (1, 95);
INSERT INTO Grade (ID, GRADE) VALUES (2, 70);
INSERT INTO Grade (ID, GRADE) VALUES (3, 85);
INSERT INTO Grade (ID, GRADE) VALUES (4, 99);
INSERT INTO Grade (ID, GRADE) VALUES (5, 91);

SELECT AVG(amount) from Students
